modules:
  # clis
  - name: zoxide
    desc: A fast alternative to cd that learns your habits
    producer: sleep 1; zoxide query --list
    consumer:
      - mod: switch_workspace 0
      - cmd: tmux new-window -c "$1"

  - name: brotab
    desc: A CLI tool to interact with the browser tabs
    prefix: "browser tab "
    producer: brotab list
    consumer:
      - cmd: brotab activate "$1"
      - mod: window_focus_title "$2"

  # workspace switching
  - name: switch_workspace_i3
    desc: Switch to a workspace by name in i3
    prefix: "i3 workspace "
    producer: i3-msg -t get_workspaces | jq -r '.[].name'
    consumer:
      - cmd: i3-msg workspace "$1"

  - name: switch_workspace_hyprland
    desc: Switch to a workspace by name in hyprland
    producer: hyprctl workspaces -j | jq '.[].id'
    consumer:
      - cmd: hyprland dispatch workspace "$1"

  - name: switch_workspace
    desc: Switch to a workspace by name
    alias: switch_workspace_i3

  # window focus by title
  - name: focus_window_title_hyprland
    desc: Focus a window by title in hyprland
    consumer:
      - cmd: hyprland dispatch focuswindow title:"$1"

  - name: focus_window_title
    desc: Focus a window by title
    alias: focus_window_title_hyprland
