modules:
  - name: zoxide
    desc: A fast alternative to cd that learns your habits
    producer: zoxide query --list
    consumer:
      - switch_workspace 0
      - tmux new-window -c "$path"

  - name: switch_workspace_i3
    desc: Switch to a workspace by name in i3
    producer: i3-msg -t get_workspaces | jq -r '.[].name'
    consumer:
      - i3-msg workspace "$1"

  - name: switch_workspace_hyprland
    desc: Switch to a workspace by name in hyprland
    producer: hyprctl workspaces -j | jq '.[].id'
    consumer:
      - hyprland dispatch workspace "$1"

  - name: switch_workspace
    desc: Switch to a workspace by name
    alias: switch_workspace_i3
