modules:
  # clis
  - name: zoxide
    desc: A fast alternative to cd that learns your habits
    producer: zoxide query --list
    consumer: |
      sel=0 switch_workspace
      tmux new-window -c "$sel"

  - name: brotab
    desc: A CLI tool to interact with the browser tabs
    prefix: "browser tab "
    producer: brotab list
    consumer: |
      IFS=$'\t' read -r id title _ <<< "$sel"
      command brotab activate "$id"
      sel="$title" focus_window_title

  # workspace switching
  - name: switch_workspace_i3
    desc: Switch to a workspace by name in i3
    prefix: "i3 workspace "
    producer: i3-msg -t get_workspaces | jq -r '.[].name'
    consumer: |
      i3-msg workspace "$sel"

  - name: switch_workspace_hyprland
    desc: Switch to a workspace by name in hyprland
    producer: hyprctl workspaces -j | jq '.[].id'
    consumer: |
      hyprland dispatch workspace "$sel"

  - name: switch_workspace
    desc: Switch to a workspace by name
    alias: switch_workspace_i3

  # window focus by title
  - name: focus_window_title_i3
    prefix: "i3 window "
    desc: Focus a window by title in i3
    producer: |
      wmctrl -l \
      | sed -E 's|\s+| |g' \
      | cut -d " " -f 4-
    consumer: |
      wmctrl -a "$sel"

  - name: focus_window_title_hyprland
    desc: Focus a window by title in hyprland
    producer: hyprctl clients -j | jq '.[].title' | sed 's;";;g'
    consumer: |
      hyprctl dispatch focuswindow title:"$sel"

  - name: focus_window_title
    desc: Focus a window by title
    alias: focus_window_title_hyprland
